name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.8

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            libncurses5:i386 \
            libstdc++6:i386 \
            libgtk2.0-0:i386 \
            libpangox-1.0-0:i386 \
            libpangoxft-1.0-0:i386 \
            libidn11:i386 \
            python2.7 \
            python2.7-dev \
            openjdk-8-jdk \
            unzip \
            zlib1g-dev \
            zlib1g:i386

      - name: Install Buildozer
        run: |
          pip install buildozer

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: bin/*.apk
